(()=>{
'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',colors=['var(--c1)','var(--c2)','var(--c3)'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=3)=>Number(v).toLocaleString('nl-BE',{maximumFractionDigits:d}),rad=d=>d*Math.PI/180;
function mathTokens(s){
 let out='',parts=s.split(/(\[\[[\s\S]*?\]\])/g);
 for(const part of parts){if(part.startsWith('[[')){const inside=part.slice(2,-2),at=inside.indexOf('|');out+='<mfrac><mrow>'+mathTokens(inside.slice(0,at))+'</mrow><mrow>'+mathTokens(inside.slice(at+1))+'</mrow></mfrac>';continue;}
 const tokens=part.match(/[A-Za-zΑ-Ωα-ωℰℱℜΦλθτμρΣ][A-Za-zΑ-Ωα-ω]*?(?:_(?:[A-Za-z0-9Α-Ωα-ω⊥∥]+))?(?:\^\d+)?(?=[^A-Za-zΑ-Ωα-ω]|$)|\d+(?:[.,]\d+)?|[^\s]/g)||[];
 for(const t of tokens){if(/^[A-Za-zΑ-Ωα-ωℰℱℜΦλθτμρΣ]/.test(t)){let value=t,exponent;if(value.includes('^'))[value,exponent]=value.split('^');const [base,sub]=value.split('_');let item='<mi>'+esc(base)+'</mi>';if(sub)item='<msub>'+item+'<mtext>'+esc(sub)+'</mtext></msub>';if(exponent)item='<msup>'+item+'<mn>'+esc(exponent)+'</mn></msup>';out+=item;}else out+=/^\d/.test(t)?'<mn>'+esc(t)+'</mn>':'<mo>'+esc(t)+'</mo>';}
 }return out;
}
function eq(s){return '<div class="eq"><math xmlns="http://www.w3.org/1998/Math/MathML" aria-label="'+esc(s.replace(/\[\[|\]\]/g,'').replace(/\|/g,' gedeeld door '))+'"><mrow>'+mathTokens(s)+'</mrow></math></div>';}
function renderLaws(){
 const text=$('search').value.trim().toLocaleLowerCase('nl'),cat=$('category').value;let count=0;
 $('law-list').innerHTML=window.GENERATOR_LAWS.map(l=>{const show=(cat==='all'||cat===l.cat)&&JSON.stringify(l).toLowerCase().includes(text);if(show)count++;const url=l.external||(l.source?'https://openstax.org/books/university-physics-volume-2/pages/'+l.source:'');return '<details id="law-'+l.id+'"'+(show?'':' hidden')+'><summary>'+esc(l.title)+'<span class="tag">'+esc(l.cat)+'</span></summary><p>'+esc(l.text)+'</p><div class="equations">'+l.eq.map(eq).join('')+'</div><p><strong>Eenheden &amp; voorwaarden:</strong> '+esc(l.units)+'</p><div class="example"><strong>Voorbeeld</strong><p>'+esc(l.example)+'</p></div><div class="note"><strong>Let op</strong><p>'+esc(l.error)+'</p></div>'+(url?'<p class="source"><a href="'+esc(url)+'" target="_blank" rel="noopener">Achtergrondbron · '+(l.external?'MIT OpenCourseWare':'OpenStax')+' (online)</a></p>':'')+'</details>';}).join('');
 $('search-status').textContent=count+' van '+window.GENERATOR_LAWS.length+' onderwerpen';
 if(text)document.querySelectorAll('#law-list details:not([hidden])').forEach(d=>d.open=true);
}
function showPage(){const name=location.hash.slice(1),page=['wetten','vectoren','rekenen','oefeningen'].includes(name)?name:'wetten';document.querySelectorAll('.sections>section').forEach(s=>s.hidden=s.id!==page);document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(page==='vectoren')drawVectors();}
function num(id,min=0,max=Infinity,optional=false){const e=$(id),raw=e.value.trim(),v=Number(raw);if(optional&&raw===''){e.removeAttribute('aria-invalid');return null;}if(raw===''||!Number.isFinite(v)||v<min||v>max||((id==='gen-p'||id==='gen-n')&&!Number.isInteger(v))){e.setAttribute('aria-invalid','true');throw Error('Controleer '+e.parentElement.textContent.trim()+': geef een geldige waarde'+(id==='gen-p'||id==='gen-n'?' als geheel getal':'')+' binnen het aangegeven bereik.');}e.removeAttribute('aria-invalid');return v;}
function output(id,fn){try{$(id).textContent=fn();$(id).classList.remove('bad');}catch(e){$(id).textContent=e.message;$(id).classList.add('bad');}}
function node(s,t,a={},text){const el=document.createElementNS(NS,t);Object.entries(a).forEach(([k,v])=>el.setAttribute(k,v));if(text!==undefined)el.textContent=text;s.appendChild(el);return el;}
function canvas(id){const s=$(id),w=Math.max(260,s.parentElement.clientWidth),h=300;s.innerHTML='';s.setAttribute('viewBox',`0 0 ${w} ${h}`);const defs=node(s,'defs');for(let i=0;i<4;i++){const m=node(defs,'marker',{id:id+'-arrow'+i,markerWidth:8,markerHeight:8,refX:7,refY:4,orient:'auto',markerUnits:'userSpaceOnUse'});node(m,'path',{d:'M0,0 L8,4 L0,8 Z',fill:i<3?colors[i]:'var(--c4)'});}return {s,w,h,cx:w/2,cy:h/2};}
function ln(s,x1,y1,x2,y2,c='var(--line)',dash=false){node(s,'line',{x1,y1,x2,y2,stroke:c,'stroke-width':dash?1:2,...(dash?{'stroke-dasharray':'4 4'}:{})});}
function arrow(s,id,x1,y1,x2,y2,i=0){if(Math.hypot(x2-x1,y2-y1)<.1)return;node(s,'line',{x1,y1,x2,y2,stroke:i<3?colors[i]:'var(--c4)','stroke-width':2.7,'marker-end':`url(#${id}-arrow${i})`});}
function label(s,x,y,t,a='middle'){node(s,'text',{x,y,'text-anchor':a},t);}
function flux(){output('flux-readout',()=>{const angle=num('flux-angle',0,180),b=num('flux-b',0,10),area=num('flux-area',.0001,10),bn=b*Math.cos(rad(angle)),bt=b*Math.sin(rad(angle));$('flux-angle-out').textContent=angle+'°';const {s,w,cx,cy}=canvas('flux-svg'),scale=b===0?0:Math.min(w*.32,100),x=cx+scale*Math.cos(rad(angle)),y=cy-scale*Math.sin(rad(angle));ln(s,18,cy,w-16,cy);ln(s,cx,25,cx,275,'var(--line)',true);arrow(s,'flux-svg',cx,cy,x,y,0);arrow(s,'flux-svg',cx,cy,x,cy,1);arrow(s,'flux-svg',x,cy,x,y,2);ln(s,cx,y,x,y,'var(--line)',true);label(s,w-20,cy+22,'n','end');label(s,cx+12,25,'spoelvlak','start');label(s,Math.max(25,Math.min(w-25,x)),Math.max(18,y-14),'B');label(s,cx,290,'n ⟂ spoelvlak');return `Bn = ${fmt(bn,6)} T\nBt = ${fmt(bt,6)} T\nΦ = BnA = ${fmt(bn*area,6)} Wb\nDe lengte van B is ${fmt(b)} T; θ = ${angle}°.`;});}
function lorentz(){output('lor-readout',()=>{const a=num('lor-angle',0,180),v=num('lor-v',0,1e7),b=num('lor-b',0,10),sign=Number($('lor-charge').value),vp=v*Math.cos(rad(a)),vt=v*Math.sin(rad(a)),force=1.602176634e-19*v*b*((a===0||a===180)?0:Math.sin(rad(a)));$('lor-angle-out').textContent=a+'°';const {s,w,cx,cy}=canvas('lor-svg'),scale=v===0?0:Math.min(w*.32,100),x=cx+scale*Math.cos(rad(a)),y=cy-scale*Math.sin(rad(a));ln(s,18,cy,w-16,cy);if(b>0)arrow(s,'lor-svg',cx,cy,w-30,cy,1);arrow(s,'lor-svg',cx,cy,x,y,0);arrow(s,'lor-svg',cx,cy,x,cy,2);ln(s,x,cy,x,y,colors[2],true);label(s,w-23,cy+24,'B','end');label(s,Math.max(20,Math.min(w-20,x)),Math.max(18,y-14),'v');const direction=force<1e-35?'geen kracht':sign>0?'⊗ in het scherm':'⊙ uit het scherm';label(s,cx,270,direction);return `v∥ = ${fmt(vp)} m/s\nv⊥ = ${fmt(vt)} m/s\n|FB| = ${force.toExponential(4)} N\nRichting: ${direction}.\nB wijst naar rechts; v ligt in het schermvlak.`;});}
function phasors(){output('phase-readout',()=>{const a=num('phase-angle',0,360),u=num('phase-u',1,1000),pair=Number($('phase-pair').value),letters=['U','V','W'];$('phase-angle-out').textContent=a+'°';const {s,w,cx,cy}=canvas('phase-svg'),scale=Math.min(w*.23,68),points=[0,1,2].map(i=>({x:u*Math.cos(rad(a-i*120)),y:u*Math.sin(rad(a-i*120))})),xy=p=>({x:cx+p.x/u*scale,y:cy-p.y/u*scale});ln(s,15,cy,w-15,cy);ln(s,cx,20,cx,285);for(let i=0;i<3;i++){const p=xy(points[i]);arrow(s,'phase-svg',cx,cy,p.x,p.y,i);const tx=cx+(p.x-cx)*1.17,ty=cy+(p.y-cy)*1.17;label(s,Math.max(22,Math.min(w-22,tx)),Math.max(16,Math.min(286,ty)),letters[i]);}const i=pair,j=(pair+1)%3,d={x:points[i].x-points[j].x,y:points[i].y-points[j].y},p1=xy(points[i]),p2=xy(points[j]),end=xy(d);ln(s,p2.x,p2.y,p1.x,p1.y,'var(--c4)',true);arrow(s,'phase-svg',cx,cy,end.x,end.y,3);label(s,Math.max(40,Math.min(w-40,end.x)),Math.max(18,Math.min(286,end.y-10)),letters[i]+letters[j]);return `Wikkelingen: U = U1–U2, V = V1–V2, W = W1–W2.\n${letters[i]}: x = ${fmt(points[i].x)} V; y = ${fmt(points[i].y)} V\n${letters[j]}: x = ${fmt(points[j].x)} V; y = ${fmt(points[j].y)} V\nVerschil: x = ${fmt(d.x)} V; y = ${fmt(d.y)} V\nGrootte = √(x² + y²) = ${fmt(Math.hypot(d.x,d.y))} V\nRelatieve hoek met ${letters[i]}: +30°.\nSom van de drie fasefasoren: 0 V (ideaal).`;});}
function drawVectors(){flux();lorentz();phasors();}
function calcGenerator(){output('gen-readout',()=>{const b=num('gen-b',0,10),a=num('gen-a',.0001,10),n=num('gen-n',1,1e5),rpm=num('gen-rpm',0,1e5),p=num('gen-p',1,20),f=p*rpm/60,phi=b*a,omega=2*Math.PI*f,peak=n*phi*omega;return `Aantal polen = ${2*p}\nf = pn/60 = ${fmt(f)} Hz\nT = ${f?fmt(1000/f)+' ms':'niet gedefinieerd bij stilstand'}\nωmechanisch = ${fmt(2*Math.PI*rpm/60)} rad/s\nωelektrisch = ${fmt(omega)} rad/s\nΦmax = BA = ${fmt(phi,6)} Wb\nEmax = NΦmaxωelektrisch = ${fmt(peak)} V\nEeff per wikkeling = ${fmt(peak/Math.SQRT2)} V\nIdeale lijnspanning in ster = ${fmt(peak/Math.SQRT2*Math.sqrt(3))} V`;});}
function calcRlc(){output('rlc-readout',()=>{const u=num('rlc-u',0,1e4),f=num('rlc-f',.1,1e5),r=num('rlc-r',.001,1e6),l=num('rlc-l',0,1e6)/1000,c=num('rlc-c',.001,1e7,true),xl=2*Math.PI*f*l,xc=c===null?0:1/(2*Math.PI*f*c/1e6),x=xl-xc,z=Math.hypot(r,x),phase=Math.atan2(x,r),i=u/z,p=i*i*r,q=i*i*x,S=u*i;return `XL = ${fmt(xl)} Ω · XC = ${c===null?'niet aanwezig':fmt(xc)+' Ω'}\nZ = ${fmt(r)} ${x<0?'−':'+'} j${fmt(Math.abs(x))} Ω\n|Z| = ${fmt(z)} Ω\nφ = ${fmt(phase*180/Math.PI)}° · cos φ = ${fmt(r/z,5)}\nIeff = ${fmt(i)} A\nP = ${fmt(p)} W · Q = ${fmt(q)} var · S = ${fmt(S)} VA\n${Math.abs(x)<1e-10?'Stroom en spanning in fase.':x>0?'Inductief: stroom loopt achter.':'Capacitief: stroom loopt voor.'}${l&&c?`\nf0 = ${fmt(1/(2*Math.PI*Math.sqrt(l*c/1e6)))} Hz`:''}`;});}
function calcPower(){output('power-readout',()=>{const u=num('power-u',0,1e5),i=num('power-i',0,1e5),pf=num('power-pf',0,1),sign=Number($('power-kind').value),S=Math.sqrt(3)*u*i,phase=sign*Math.acos(pf);return `φ = ${fmt(phase*180/Math.PI)}°\nS = √3 UL IL = ${fmt(S)} VA\nP = S cos φ = ${fmt(S*pf)} W\nQ = S sin φ = ${fmt(S*Math.sin(phase))} var\nSter: Uf = ${fmt(u/Math.sqrt(3))} V; If = ${fmt(i)} A\nDriehoek: Uf = ${fmt(u)} V; If = ${fmt(i/Math.sqrt(3))} A`;});}
function exercises(){
 $('exercise-list').innerHTML=window.GENERATOR_EXERCISES.map((e,i)=>`<article class="exercise"><h3>${i+1} · ${esc(e.title)}</h3><p>${esc(e.q)}</p><div class="answer-row"><label>Antwoord (${esc(e.unit)})<input id="answer-${i}" type="text" inputmode="decimal" autocomplete="off"></label><button type="button" data-check="${i}">Controleer</button></div><p class="feedback" id="feedback-${i}" aria-live="polite"></p><details><summary>Eén hint</summary><p>${esc(e.hint)}</p></details><details><summary>Uitwerking</summary><p>${esc(e.solution)}</p></details></article>`).join('');
 document.querySelectorAll('[data-check]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.check),e=window.GENERATOR_EXERCISES[i],raw=$('answer-'+i).value.trim().replace(',','.'),v=Number(raw),feedback=$('feedback-'+i);if(!raw||!Number.isFinite(v)){feedback.textContent='Geef een getal in, bijvoorbeeld 0,006 of 2e-5.';feedback.className='feedback bad';return;}const ok=Math.abs(v-e.answer)<=Math.abs(e.answer)*.01+1e-12;feedback.textContent=ok?'Correct binnen 1% afrondingsmarge. '+e.solution:'Nog niet correct. '+e.wrong;feedback.className='feedback '+(ok?'good':'bad');}));
}
$('symbols').innerHTML=[['U, u, E','effectieve, momentane of geïnduceerde spanning · V'],['I, i','effectieve of momentane stroom · A'],['R, Z, XL, XC','weerstand, impedantie en reactantie · Ω'],['B, Φ, λ','inductie · T; flux · Wb; fluxkoppeling · Wb·winding'],['A, Adraad','spoeloppervlak of draaddoorsnede · m²'],['N, p, n','windingen, poolparen, toerental · omw/min'],['f, T, ω','frequentie · Hz; periode · s; hoeksnelheid · rad/s'],['θ, α, φ','geometrische hoek of fasehoek · graden/rad'],['P, Q, S','werkelijk · W; reactief · var; schijnbaar · VA'],['τ, J, η','koppel · N·m; traagheidsmoment · kg·m²; rendement'],['L, C, q','inductantie · H; capaciteit · F; lading · C'],['U1/U2, V1/V2, W1/W2','begin/einde van de drie wikkelingen; L1/L2/L3 zijn voedingslijnen']].map(([s,d])=>'<p><strong>'+esc(s)+'</strong><br>'+esc(d)+'</p>').join('');
$('search').addEventListener('input',renderLaws);$('category').addEventListener('change',renderLaws);$('expand').addEventListener('click',()=>{const list=[...document.querySelectorAll('#law-list details:not([hidden])')],open=!list.every(d=>d.open);list.forEach(d=>d.open=open);$('expand').textContent=open?'Alles sluiten':'Alles openen';});
for(const [ids,fn] of [[['flux-angle','flux-b','flux-area'],flux],[['lor-angle','lor-v','lor-b','lor-charge'],lorentz],[['phase-angle','phase-u','phase-pair'],phasors],[['gen-b','gen-a','gen-n','gen-rpm','gen-p'],calcGenerator],[['rlc-u','rlc-f','rlc-r','rlc-l','rlc-c'],calcRlc],[['power-u','power-i','power-pf','power-kind'],calcPower]])for(const id of ids)$(id).addEventListener('input',fn);
window.addEventListener('hashchange',showPage);new ResizeObserver(()=>{if(!$('vectoren').hidden)drawVectors();}).observe($('vectoren'));
renderLaws();exercises();showPage();calcGenerator();calcRlc();calcPower();
window.GeneratorPhysics={flux:(b,a,d)=>b*a*Math.cos(rad(d)),lorentz:(q,v,b,d)=>Math.abs(q)*v*b*Math.sin(rad(d)),lineVoltage:u=>u*Math.sqrt(3),generator:(b,a,n,rpm,p)=>n*b*a*2*Math.PI*p*rpm/60/Math.SQRT2,formatFormula:eq};
})();
